name: CI
on: pull_request
jobs:
  test:
    name: Lint/Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Set up node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: |
          npm i
          npm i @web/test-runner-playwright --no-save
          npx playwright install-deps
      - name: Lint
        run: npm run lint
      - name: Test (Cross Browser)
        run: npx web-test-runner --files ./test/**/*.test.js --node-resolve --playwright --browsers chromium firefox webkit
